#pragma config(Sensor, S4,     ,               sensorEV3_IRSensor, modeEV3IR_Remote)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1){
	if (getIRRemoteButtons (S4)==1){
		setMotorSpeed (motorA,20);
	}
	else {
		setMotorSpeed(motorA,0);

}
}
}
