#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void faireTournerMobilex() {
//Synchronise les deux moteurs à 40% de la puissance avec un ratio de 100.
setMotorSync(motorA,motorD,100,50);
        //Attente de 400ms.
	sleep(400);
	}
task main()
{
	        SensorType[S1] = sensorEV3_Touch;
	 	SensorType[S2] = sensorEV3_Touch;
	    	SensorType[S3] = sensorEV3_Touch;
	        SensorType[S4] = sensorEV3_Ultrasonic;

	 while((getButtonPress(buttonUp)==false)||(getButtonPress(buttonDown)==false)){      //boucle de fonctionement (choix du mode)
         //Affiche à la ligne 3 le message "En haut mode manuel".
	  displayText(3,"En haut mode manuel");
          //Affiche à la ligne 6 le message "En bas mode automatique".
	  displayText(6,"En bas mode automatique");
          //Attente pendant 3ms.
	  sleep(3000);
	  int mode=0 ;
	  if (getButtonPress(buttonUp)==true){
	    	mode=1;
	  }
	  if (getButtonPress(buttonDown)==true){
	        mode=2;
	  }
	  while (mode==1){     //mode manuel
                //Affiche à la ligne 2 au centre le message "mode manuel".
	   	displayCenteredBigTextLine(2,"mode manuel");

	   if (getButtonPress(buttonDown)==true){
	       mode=2; // on sort du mode manuel et on effectue le mode automatique, cette condition est toujours à vérifier
	   }


	    while (SensorValue[S1]==1){
                //Le moteur A est en avant à 40%.
	        setMotorSpeed(motorA,-40);
                //Le moteur D est en avant à 40%.
	        setMotorSpeed(motorD,40);
                //Attente pendant 1000ms.
	        sleep(1000);

	     if(SensorValue[S1]==0){
              //Arrêt du moteur A.
	        stopMotor(motorA);
              //Arrêt du moteur D.
	        stopMotor(motorD);
	     }
	    }
	    while ((SensorValue[S2]==1)&&(SensorValue[S1]==1)){
             //Le moteur A est en arrière à 40%.
	      setMotorSpeed(motorA,40);
             //Le moteur D est en arrière à 40%.
	      setMotorSpeed(motorD,-40);
             //Attente pendant 1000ms.
	      sleep(1000);

	      if ((SensorValue[S2]==0)&&(SensorValue[S1]==0)){
               //Arrêt du moteur A.
	        stopMotor(motorA);
               //Arrêt du moteur D.
	        stopMotor(motorD);

	      }
	    }
	    while (SensorValue[S2]==1){
             //Le moteur A est en arrière à 30%.
	      setMotorSpeed(motorA,20);
             //Le moteur D est en avant à 30%.
	      setMotorSpeed(motorD,20);
             //Attente pendant 1000ms.
	      sleep(1000);

	      if(SensorValue[S2]==0){
               //Arrêt du moteur A.
	        stopMotor(motorA);
               //Arrêt du moteur D.
	        stopMotor(motorD);

	      }
	    }
	    while (SensorValue[S3]==1){
             //Le moteur A est en avant à 30%.
	      setMotorSpeed(motorA,-20);
             //Le moteur D est en arrière à 30%.
	      setMotorSpeed(motorD,-20);
             //Attente pendant 1000ms.
	      sleep(1000);

	      if(SensorValue[S3]==0){
               //Arrêt du moteur A.
	        stopMotor(motorA);
                //Arrêt du moteur D.
	        stopMotor(motorD);

	      }
	    }
	  }

	 while(mode==2){
	  if (getButtonPress(buttonUp)==true){
	    mode=1;//pour changer en mode manuel
	  }
          //Affiche le message "Mode automatique" à la ligne 5.
	  displayBigTextLine(5,"Mode automatique");
	  setSensorMode(S4,modeEV3Ultrasonic_Cm);
	  float x;
	  x = SensorValue[S4];
	   //Le moteur A est en avant à 40%.
	  setMotorSpeed(motorA,-40);
         //Le moteur D est en avant à 40%.
	  setMotorSpeed(motorD,40);
         //joue le son  nommé « soundBeepBeep »
	  playSound(soundBeepBeep);
	 //Règle le volume à 50%.
	  setSoundVolume(50);

	  while((x <=10) &&( mode == 2)){
          //Le moteur A est en arrière à 30%.
	    setMotorSpeed(motorA,30);
           //Le moteur D est en arrière à 30%.
	    setMotorSpeed(motorD,-30);
            //Attente pendant 1000ms.
	    sleep(1000);
            //Le moteur A est en avant à 30%.
	    setMotorSpeed(motorA,-30);
            //Le moteur D est en arrière à 30%.
	    setMotorSpeed(motorD,-30);
	    x = SensorValue[S1];
	    if ( x <= 10 ) {
        //Arrêt de tous les moteurs
	    	stopAllMotors();
	    	//Affiche le message "Appuyez sur les boutons corrects" à la ligne5.
	    	displayTextLine(10,"Appuyez sur le boutons corrects");
	    	//Attente de 5000ms.
	    	sleep(5000);
}
	    	if(getButtonPress(buttonLeft)==true){
	    			mode = 1;
	    		faireTournerMobilex();
	    		//Si on appuie sur le bouton poussoir gauche de la brique le système mobile tourne .
	    		sleep(2000);

	    }else {
	    	mode = 1;
                //Affiche le message "Incorrect!" à la ligne5.
	    	displayTextLine(14,"Incorrect!");
	    	//Attente de 1000ms.
	    	sleep(2000) ;

	    }




}}}}
