

#pragma config(Sensor, S4,     ,               sensorEV3_IRSensor, modeEV3IR_Remote)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void faireTournerMobilex() {
//Synchronise les deux moteurs à 50% de la puissance avec un ratio de 100.
setMotorSync(motorA,motorD,100,50);
        //Attente de 400ms.
	sleep(400);
	}
task main()
{ int mode = 1 ;
	float k , r;
	float h ,w , y;
	while ( mode == 1){
		if (getIRRemoteButtons(S4) == 5){
			float n;
			//Le moteur A est en arrière à 20%.
			setMotorSpeed(motorA,-20);
			//Le moteur A est en avant à 20% .
			setMotorSpeed(motorD,20);
			//Renvoie le nombre de degrés effectués par le moteur D.
			n = getMotorEncoder(motorD);
			k = n*60;
			sleep(1000);
			}else {
			//Le moteur A est à 0%.
			setMotorSpeed(motorA,0);
			//Le moteur D est à 0%.
			setMotorSpeed(motorD,0);
			sleep(1000);
		}
		if (getIRRemoteButtons(S4) ==8) {float b;
			//Le moteur A est en avant à 20% .
			setMotorSpeed(motorA, 20);
			//Le moteur A est en arrière à 20%.
			setMotorSpeed(motorD, -20);
			b = getMotorEncoder(motorA);
			h = b*60 ;
			sleep(1000);
			}else {
			//Le moteur A est à 0%.
			setMotorSpeed(motorA,0);
			//Le moteur D est à 0%.
			setMotorSpeed(motorD,0);
			sleep(1000);
		}

		if (getIRRemoteButtons(S4)==10){
			float c;
			//Le moteur A est en arrière à 20%.
			setMotorSpeed(motorA, - 20);
			//Le moteur D est en arrière à 20%.
			setMotorSpeed(motorD, - 20);
			c = getMotorEncoder(motorA);
			r = c*60;
			//Attente de 100ms.
			sleep(1000);
			}else {
			//Le moteur A est à 0%.
			setMotorSpeed(motorA,0);
			//Le moteur D est à 0%.
			setMotorSpeed(motorD,0);
			//Attente de 1000ms.
			sleep(1000);
		}
		if (getIRRemoteButtons(S4) == 11) {
			float d;
			//Le moteur A est en avant à 20%.
			setMotorSpeed(motorA, 20);
			//Le moteur D est en avant à 20%.
			setMotorSpeed(motorD, 20);
			d = getMotorEncoder(motorD);
			w = d*60;
			sleep(1000);
			}else {
			//Le moteur A est à 0%.
			setMotorSpeed(motorA,0);
			//Le moteur D est à 0%.
			setMotorSpeed(motorD,0);
			//Attente de 1000ms.
			sleep(1000);
		}
		if (getIRRemoteButtons(S4) == 7) {
			mode = 2;
			//Attente de 1000ms.
			sleep(1000);
		}
	}
	while(mode==2){
		if (getButtonPress(buttonUp)==true){
			mode=1;//pour changer en mode manuel
		}
		//Affiche le message "Mode automatique" à la ligne 5.
		displayBigTextLine(5,"Mode automatique");
		setSensorMode(S4,modeEV3Ultrasonic_Cm);
		float x;
		x = SensorValue[S4];
		//Le moteur A est en avant à 40%.
		setMotorSpeed(motorA,-40);
		//Le moteur D est en avant à 40%.
		setMotorSpeed(motorD,40);
		//joue le son  nommé « soundBeepBeep »
		playSound(soundBeepBeep);
		//Règle le volume à 50%.
		setSoundVolume(50);

		while((x <=10) &&( mode == 2)){
			//Le moteur A est en arrière à 30%.
			setMotorSpeed(motorA,30);
			//Le moteur D est en arrière à 30%.
			setMotorSpeed(motorD,-30);
			//Attente pendant 1000ms.
			sleep(1000);
			//Le moteur A est en avant à 30%.
			setMotorSpeed(motorA,-30);
			//Le moteur D est en arrière à 30%.
			setMotorSpeed(motorD,-30);
			x = SensorValue[S1];
			if ( x <= 10 ) {
				//Arrêt de tous les moteurs
				stopAllMotors();
				//Affiche le message "Appuyez sur les boutons corrects" à la ligne5.
				displayTextLine(10,"Appuyez sur le boutons corrects");
				//Attente de 5000ms.
				sleep(5000);
			}
			if(getButtonPress(buttonLeft)==true){
				mode = 1;
				faireTournerMobilex();
				//Si on appuie sur le bouton poussoir gauche de la brique le système mobile tourne .
				//Attente de 2000ms.
				sleep(2000);

				}else {
				mode = 1;
				//Affiche le message "Incorrect!" à la ligne5.
				displayTextLine(14,"Incorrect!");
				//Attente de 1000ms.
				//Attente de 2000ms.
				sleep(2000) ;

			}
			y = y - 10;
		}
		k= k + h+ r+ w + y;
		//Arrêt de tous les moteurs
		stopAllMotors () ;
		//Affiche la valeur de la variable k à la ligne 10.
		displayVariableValues(10,k);
		//Attente pendant 2000ms.
		sleep(2000);
	}
}
