#pragma config(Sensor, S4,     ,               sensorEV3_IRSensor, modeEV3IR_Remote)
#pragma config(Motor,  motorA,           ,             tmotorEV3_Large, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void faireTournerMobilex()
	{
	int y ;
setMotorSync(motorA,motorD,100,40);
	sleep(400);
	y = y - 10;
	displayVariableValues(10,y);
sleep(800);
}
task main()
{int x , y ;
	SensorType[S1] = sensorEV3_Ultrasonic;
	setSensorMode(S4,modeEV3Ultrasonic_Cm);
	x = SensorValue[S1];
		y = SensorValue[S1];
	displayVariableValues(10,x);
	while ( x >= 10) {
		x = SensorValue[S1];
			displayVariableValues(10,x);
		setMotorSpeed(motorA,-75);
		setMotorSpeed(motorD,75);
		playSound(soundBeepBeep);
	  setSoundVolume(50);
	}
	stopAllMotors();
	displayTextLine(5,"Appuyez sur le boutons corrects");
	sleep(1000);
	if(getButtonPress(buttonLeft)==true){
		faireTournerMobilex();
}
}
