#pragma config(Sensor, S4,     ,               sensorEV3_IRSensor, modeEV3IR_Remote)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	 float k , r;
	 float h ,w ;
	 while (1){
if (getIRRemoteButtons(S4) == 1)&& (getIRRemoteButtons(S4) == 3){
float n;
setMultipleMotors(20,motorA,motorD);
n = getMotorEncoder(motorA);
k = n*60;
}else(getIRRemoteButtons(S4) == 2)&&(getIRRemoteButtons(S4) == 4) {float b;
  tMotorSpeed(motorA, -20);
setMotorSpeed(motorD, -20);
b = getMotorEncoder(motorA);
h = b*60;
}else {
	setMotorSpeed(motorA,0);
setMotorSpeed(motorD,0);
}
if (getIRRemoteButtons(S4)==1)&&(getIRRemoteButtons(S4) == 2){
	float c;
	setMotorSpeed(motorA, 20);
setMotorSpeed(motorD,0);
c = getMotorEncoder(motorA);
r = c*60;
	}else if (getIRRemoteButtons(S4) == 3)&&(getIRRemoteButtons(S4) == 4) {
float d;
	setMotorSpeed(motorA, 0);
setMotorSpeed(motorD, 20);
d = getMotorEncoder(motorA);
w = c*60;
}else {
	setMotorSpeed(motorA,0);
setMotorSpeed(motorD,0);
}
k= k+h+r+w;
stopAllMotors () ;
displayVariableValues(10,k);
sleep(2000);
}
}
