#pragma config(Sensor, S4,     ,               sensorEV3_IRSensor, modeEV3IR_Remote)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
	{ int mode = 1 ;
		 float k , r;
		 float h ,w , y;
		 while ( mode == 1){
	if (getIRRemoteButtons(S4) == 5){
	float n;
        //Le moteur A est en arrière à 20%.
	setMotorSpeed(motorA,-20);
        //Le moteur A est en avant à 20% .
	setMotorSpeed(motorD,20);
        //Renvoie le nombre de degrés effectués par le moteur D.
	n = getMotorEncoder(motorD);
	k = n*60;
	sleep(3000);
	}else {
        //Le moteur A est à 0%.
		setMotorSpeed(motorA,0);
        //Le moteur D est à 0%.
	setMotorSpeed(motorD,0);
	sleep(1000);
	}
	if (getIRRemoteButtons(S4) ==8) {float b;
         //Le moteur A est en avant à 20% .
	  setMotorSpeed(motorA, 20);
        //Le moteur A est en arrière à 20%.
	setMotorSpeed(motorD, -20);
	b = getMotorEncoder(motorA);
	h = b*60 ;
	sleep(3000);
	}else {
         //Le moteur A est à 0%.
		setMotorSpeed(motorA,0);
        //Le moteur D est à 0%.
	setMotorSpeed(motorD,0);
	sleep(1000);
	}

	if (getIRRemoteButtons(S4)==10){
		float c;
        //Le moteur A est en arrière à 20%.
	setMotorSpeed(motorA, - 20);
        //Le moteur D est en arrière à 20%.
	setMotorSpeed(motorD, - 20);
	c = getMotorEncoder(motorA);
	r = c*60;
	sleep(3000);
	}else {
        //Le moteur A est à 0%.
		setMotorSpeed(motorA,0);
       //Le moteur D est à 0%.
	setMotorSpeed(motorD,0);
	sleep(1000);
	}
	if (getIRRemoteButtons(S4) == 11) {
	float d;
        //Le moteur A est en avant à 20%.
		setMotorSpeed(motorA, 20);
        //Le moteur D est en avant à 20%.
	setMotorSpeed(motorD, 20);
	d = getMotorEncoder(motorD);
	w = d*60;
	sleep(3000);
	}else {
        //Le moteur A est à 0%.
	setMotorSpeed(motorA,0);
        //Le moteur D est à 0%.
	setMotorSpeed(motorD,0);
	sleep(1000);
	}
	if (getIRRemoteButtons(S4) == 7) {
      mode = 2;
      sleep(1000);
	}
		 }
	 while(mode==2){
	 SensorType[S1] = sensorEV3_Ultrasonic;
         //Affiche à la ligne 5 le message "Parking automatique".
	  displayBigTextLine(5,"Parking automatique");
	  setSensorMode(S1,modeEV3Ultrasonic_Cm);
	  float x;
		x = SensorValue[S1];
		y = SensorValue[S1];
                //Affiche à la ligne 10 la valeur de x.
		displayVariableValues(10,x);
		while ( x >= 10) {
			x = SensorValue[S1];
                        //Affiche à la ligne 10 la valeur de x.
			displayVariableValues(10,x);
                        //Le moteur A est en arrière à 75%.
			setMotorSpeed(motorA,-75);
                        //Le moteur D est en avant à 75%.
			setMotorSpeed(motorD,75);
		}
                //Synchronise les 2 moteurs A et D à 40% de la puissance avec un ratio de 100.
		setMotorSync(motorA,motorD,100,40);
                //Attente de 400ms.
		sleep(400);
		y = y - 10;
	}
	k= k + h+ r+ w + y;
        //Arrêt de tous les moteurs
	stopAllMotors () ;
        //Affiche la valeur de la variable k à la ligne 10.
	displayVariableValues(10,k);
        //Attente pendant 2000ms.
	sleep(2000);
	}
