#pragma config(Sensor, S4,     ,               sensorEV3_IRSensor, modeEV3IR_Remote)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
int y, m ;
SensorType[S1] = sensorEV3_Ultrasonic;
	setSensorMode(S4,modeEV3Ultrasonic_Cm);
y = SensorValue[S1];
	displayVariableValues(10,y);
	sleep(2000);
	if ( getMotorSpeed(motorA)== 0 && getMotorSpeed(motorD)== 0 ){
	m = SensorValue[S1];
	displayVariableValues(10,m);
	sleep(2000);
	y = y - m;
	displayVariableValues(10,y);
	sleep(2000);
}
}
